version: '3'
services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-20
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - mongo
      - neo4j

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474" # Neo4j web interface
      - "7687:7687" # Bolt protocol
    environment:
      NEO4J_AUTH: "neo4j/sets-centimeters-particle"
